name: Deploy EKS Infrastructure

on:
  workflow_dispatch:

jobs:

  deploy-eks:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Ejecutar EKS Script
        run: |
          chmod +x ./scripts/crear-eks.sh
          ./scripts/crear-eks.sh